nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://github.com/mskelton/yarn-plugin-outdated/raw/v1.1.0/bundles/@yarnpkg/plugin-outdated.js"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
